apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $resource_name
spec:
  ingressClassName: $ingress_class
  rules:
  - host: $host
    http:
      paths:
      - path: $path
        pathType: Prefix
        backend:
          service:
            name: $resource_name
            port:
              number: $service_port
